### ISSUE TITLE
Add the ability to configure javascript allowed

### ISSUE THREAD

**Issue by moshthepitt** [onaio/superset-patchup#10]
Make it possible the ability to configure javascript allowed for Superset i.e. set `ENABLE_JAVASCRIPT_CONTROLS` to `True`

**Comment by pld** [comment]
Can't this go in the playbook?

**Comment by moshthepitt** [comment]
@pld yes it can and I think it already is in the playbook.

But we need it here as well as this is the tool that we will be using to create a nicer superset_config.py file for the docker-based deployment and I am hoping that at some point it will be used in the playbook/role.

This is an issue that better describes the goal here: https://github.com/onaio/canopy/issues/172

**Comment by pld** [comment]
I don't understand why we'd need it here if it's in the role and we're going to be using the role in the future to do the docker-based deploys

**Comment by moshthepitt** [comment]
Some of the changes that we are doing to Superset include things such as adding views e.g. the CSV slice view that @Wambere added a few weeks ago.  We might do more and more of these.

These kinds of "patches" can't be handled well by the playbooks/role alone in my view.

So that is why this repo exists, the main goals:

- it will be a Python package that will patch superset via a Flask blueprint
- it will produce a superset_config.py file that is aware of the patches in the blueprint
- it will ensure that we are future-proof i.e. more similar patches will be added here to the same blueprint or adjacent ones
- In the far future, this is how we will do the `config.py` file that is in the Superset role.  Putting custom configs directly in the config.py (as we do in the role right now) is not the recommended way and I'd like us to move to a superset_config.py - which is the recommended approach to custom Superset configs.  This means that my vision for this repo is a Python package that will be used by our docker-based deployments right now and later on by our ansible-based deployments

Does this make sense?

**Comment by pld** [comment]
Yes that makes sense, and I'm on board with that.

My comment is only about this specific issue, is there a reason why this specifically can't be handled by a change to the role?

**Comment by moshthepitt** [comment]
I think at least for a while longer we'll still be having some docker-based deploys of Superset that would need this, which would be an improvement over [how it is done currently](https://github.com/onaio/docker-compose-canopy/blob/master/config/services/superset/superset_config.py).

**Comment by moshthepitt** [comment]
The role already has this setting https://github.com/onaio/ansible-superset/pull/21

**Comment by pld** [comment]
Great, so my main point here is I don't want us duplicating what we have working in a role in a docker-build, I want us to commit to one, or the other, or an architecture that unifies a significant portion of the config overlap.

I.e. figure out the above instead of this issue, so I would consider this issue blocked.

**Comment by moshthepitt** [comment]
I think that makes sense.  

I'm going to write up a clearer issue/comment/plan on how I see that this repo is the architecture that unifies a significant portion of the config overlap that we all want.

**Comment by moshthepitt** [comment]
@pld I'm going to close this issue - you were right, it is not to be done by superset patchup. It should be done during deployment or by a deployment script when installing superset.
